# Generated by Django 5.1.4 on 2025-05-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('credit', 'Credit Card')], default='momo', max_length=20),
        ),
    ]
