# Generated by Django 5.1.4 on 2025-05-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_phone_number_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freelancer_cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='freelancer_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_freelancer_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hiring_company_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vendor_role',
            field=models.BooleanField(default=False),
        ),
    ]
