# Generated by Django 5.2 on 2025-07-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_purchase_payment_method"),
    ]

    operations = []
