# Generated by Django 5.2.7 on 2025-10-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_fix_category_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('books_media', 'Books & Media'), ('home_kitchen', 'Home & Kitchen'), ('beauty_care', 'Beauty & Personal Care'), ('software_services', 'Software & Services'), ('health_fitness', 'Health & Fitness'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
