# Generated by Django 5.2 on 2025-10-27 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="koraquest_commission_amount",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="koraquest_commission_sent",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="koraquest_user",
        ),
        migrations.AddField(
            model_name="purchase",
            name="kickslife250_commission_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="kickslife250_commission_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchase",
            name="kickslife250_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Kicks_life 250 user handling this purchase",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kickslife250_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("sneakers", "Sneakers"),
                    ("boots", "Boots"),
                    ("formal", "Formal Shoes"),
                    ("sandals", "Sandals & Slippers"),
                    ("athletic", "Athletic & Sports"),
                    ("casual", "Casual Shoes"),
                    ("kids", "Kids Shoes"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("pickup", "Pickup from Kicks_life 250"),
                    ("delivery", "Home Delivery"),
                ],
                default="pickup",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("staff", "Staff"),
                    ("vendor", "Vendor"),
                    ("kickslife250", "Kicks_life 250"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
