# Generated by Django 5.2 on 2025-10-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_remove_purchase_koraquest_commission_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userqrcode",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="kickslife250_commission_amount",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="kickslife250_commission_sent",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="kickslife250_user",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="pickup_confirmed_at",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="vendor_payment_amount",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="vendor_payment_sent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_vendor_role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="total_sales",
        ),
        migrations.AddField(
            model_name="purchase",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Order notes or special instructions", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                help_text="Tracking number for shipped orders",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="delivery_method",
            field=models.CharField(
                choices=[("pickup", "Store Pickup"), ("delivery", "Home Delivery")],
                default="pickup",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("momo", "Mobile Money"),
                    ("credit", "Credit Card"),
                    ("cash", "Cash on Delivery"),
                ],
                default="momo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("customer", "Customer"), ("admin", "Admin/Store Owner")],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="OTPVerification",
        ),
        migrations.DeleteModel(
            name="UserQRCode",
        ),
    ]
