# Generated by Django 5.1.4 on 2025-05-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='inventory',
            field=models.IntegerField(default=1, help_text='Number of items in stock'),
        ),
    ]
