# Generated by Django 5.2 on 2025-12-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="delivery_method",
            field=models.CharField(
                choices=[("delivery", "Home Delivery")],
                default="delivery",
                max_length=20,
            ),
        ),
    ]
