# Generated by Django 5.2 on 2025-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_purchase_delivery_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="EUR shoe size (e.g., 42, 43, 44)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="EUR shoe size (e.g., 42, 43, 44)",
                max_length=10,
                null=True,
            ),
        ),
    ]
