# Generated by Django 5.2 on 2025-12-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_cartitem_size_purchase_size"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "size")},
        ),
    ]
