"""
Django settings for Kicks_life 250 project.

Generated by 'django-admin startproject' using Django 5.1.4.
Kicks_life 250 - Your Premier Shoe Marketplace in Rwanda

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-yg!+2gbi#185v4j8r!qg&@+%mrl*qti5&1c!7y-sx0d)n(yj&@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
# DEBUG = True

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Add render domain if available
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Add PythonAnywhere domain if available (detect from environment or server name)
PYTHONANYWHERE_USERNAME = os.environ.get('PYTHONANYWHERE_USERNAME', 'kickslife250')  # Default to kickslife250
if PYTHONANYWHERE_USERNAME:
    # Add PythonAnywhere subdomain
    pythonanywhere_domain = f'{PYTHONANYWHERE_USERNAME}.pythonanywhere.com'
    if pythonanywhere_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(pythonanywhere_domain)

# Also check if we're running on PythonAnywhere by checking the server name
# This is useful if PYTHONANYWHERE_USERNAME is not set
import socket
try:
    hostname = socket.gethostname()
    if 'pythonanywhere' in hostname.lower():
        # Extract username from hostname if possible
        if '.' in hostname:
            pythonanywhere_domain = hostname
            if pythonanywhere_domain not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(pythonanywhere_domain)
except:
    pass

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000'
]

# Add production domains to CSRF trusted origins
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Add PythonAnywhere domains to CSRF trusted origins
# Always add kickslife250.pythonanywhere.com
pythonanywhere_domain = 'kickslife250.pythonanywhere.com'
if pythonanywhere_domain not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.extend([
        f'https://{pythonanywhere_domain}',
        f'http://{pythonanywhere_domain}'
    ])
if PYTHONANYWHERE_USERNAME:
    pythonanywhere_domain = f'{PYTHONANYWHERE_USERNAME}.pythonanywhere.com'
    if pythonanywhere_domain not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.extend([
            f'https://{pythonanywhere_domain}',
            f'http://{pythonanywhere_domain}'
        ])

# Detect PythonAnywhere custom domain from HTTP_HOST (when custom domain is configured)
# This works when PythonAnywhere forwards the custom domain
try:
    import socket
    # Check if we're on PythonAnywhere and get the actual hostname
    hostname = socket.gethostname()
    if 'pythonanywhere' in hostname.lower():
        # If CUSTOM_DOMAIN is set, it will be added below
        # But we also want to detect it from the request if possible
        pass
except:
    pass

# Add Fly.io domain if available
FLY_APP_NAME = os.environ.get('FLY_APP_NAME')
if FLY_APP_NAME:
    fly_domain = f'{FLY_APP_NAME}.fly.dev'
    if fly_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(fly_domain)
    CSRF_TRUSTED_ORIGINS.extend([
        f'https://{fly_domain}',
        f'http://{fly_domain}'
    ])

# Add custom domain (e.g., kickslife250.com) if specified
# This is used for PythonAnywhere Hacker plan custom domains
CUSTOM_DOMAIN = os.environ.get('CUSTOM_DOMAIN')
if CUSTOM_DOMAIN:
    # Remove any protocol if accidentally included
    CUSTOM_DOMAIN = CUSTOM_DOMAIN.replace('https://', '').replace('http://', '').strip()
    # Add both with and without www
    for domain in [CUSTOM_DOMAIN, f'www.{CUSTOM_DOMAIN}']:
        if domain not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(domain)
        CSRF_TRUSTED_ORIGINS.extend([
            f'https://{domain}',
            f'http://{domain}'
        ])

# Add custom domain directly (kickslife250.com) - hardcoded for PythonAnywhere
# This ensures the domain is always allowed even if CUSTOM_DOMAIN env var is not set
CUSTOM_DOMAINS = ['kickslife250.com', 'www.kickslife250.com']
for domain in CUSTOM_DOMAINS:
    if domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(domain)
    CSRF_TRUSTED_ORIGINS.extend([
        f'https://{domain}',
        f'http://{domain}'
    ])

# CSRF Configuration
CSRF_COOKIE_SECURE = not DEBUG  # Secure in production
CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript access
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

# For nginx reverse proxy and Render
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Security settings for production
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'authentication',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'KoraQuest.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KoraQuest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use PostgreSQL in production (Render), SQLite in development
if os.environ.get('DATABASE_URL'):
    # Production database (PostgreSQL on Render)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development database (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

AUTH_USER_MODEL = 'authentication.User'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# WhiteNoise settings for efficient static file serving
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration for OTP
if DEBUG:
    # For development, use console backend to see emails in terminal
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # For production, use SMTP backend
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'KoraQuest <noreply@koraquest.com>')

# QR Code Settings - Removed (not used)
# QR_CODE_UPDATE_INTERVAL = 600  # 10 minutes in seconds

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# CORS Settings
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS', 
    'http://localhost,http://127.0.0.1:3000'
).split(',')

# Add Render domain to CORS if available
if RENDER_EXTERNAL_HOSTNAME:
    CORS_ALLOWED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Add PythonAnywhere domain to CORS if available
# Always add kickslife250.pythonanywhere.com
pythonanywhere_domain = 'kickslife250.pythonanywhere.com'
CORS_ALLOWED_ORIGINS.extend([
    f'https://{pythonanywhere_domain}',
    f'http://{pythonanywhere_domain}'
])
if PYTHONANYWHERE_USERNAME:
    pythonanywhere_domain = f'{PYTHONANYWHERE_USERNAME}.pythonanywhere.com'
    if f'https://{pythonanywhere_domain}' not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.extend([
            f'https://{pythonanywhere_domain}',
            f'http://{pythonanywhere_domain}'
        ])
    # Also add custom domain if set
    if CUSTOM_DOMAIN:
        for domain in [CUSTOM_DOMAIN, f'www.{CUSTOM_DOMAIN}']:
            CORS_ALLOWED_ORIGINS.extend([
                f'https://{domain}',
                f'http://{domain}'
            ])

# Add Fly.io domain to CORS if available
if FLY_APP_NAME:
    fly_domain = f'{FLY_APP_NAME}.fly.dev'
    CORS_ALLOWED_ORIGINS.extend([
        f'https://{fly_domain}',
        f'http://{fly_domain}'
    ])

# Add custom domain to CORS if available
if CUSTOM_DOMAIN:
    for domain in [CUSTOM_DOMAIN, f'www.{CUSTOM_DOMAIN}']:
        CORS_ALLOWED_ORIGINS.extend([
            f'https://{domain}',
            f'http://{domain}'
        ])

# Add custom domain directly to CORS (kickslife250.com) - hardcoded for PythonAnywhere
for domain in CUSTOM_DOMAINS:
    CORS_ALLOWED_ORIGINS.extend([
        f'https://{domain}',
        f'http://{domain}'
    ])

CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for development
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True  # Only for development!
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
    ]

# CORS headers that are allowed
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CORS methods that are allowed
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]